# fly.toml app configuration file generated for login1 on 2023-07-19T18:47:18-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "login1"
primary_region = "dfw"

[http_service]
  internal_port = 9012
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
